apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: build-m4-component
  labels:
    pipelines.appstudio.openshift.io/type: build
    build.appstudio.openshift.io/component: m4-component
  namespace: demo
spec:
  pipelineRef:
    name: m4-build-pipeline
    bundle: quay.io/hacbs-release/m4:0.1-alpine
