apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: m4-component
  namespace: demo
spec:
  componentName: m4-component
  application: m4-app
  source:
    git:
      url: https://github.com/sbose78/devfile-sample-code-with-quarkus
  build:
    containerImage: quay.io/release-e2e/devfile-sample-code-with-quarqus:dev-code-with-quarkus
